Repository the-chance-buenos-aires-squad/planMate, pull requests merged in 2025-05, with the labels that each got.

#97 Task/88 create task cli
  src/main/kotlin/di/presentationModule.kt
  src/main/kotlin/domain/usecases/task/CreateTaskUseCase.kt
  src/main/kotlin/presentation/cli/task/CreateTaskCli.kt
  src/test/kotlin/domain/usecases/task/CreateTaskUseCaseTest.kt
  src/test/kotlin/dummyData/DummyTaskData.kt
  src/test/kotlin/presentation/cli/task/CreateTaskCliTest.kt
Labels: Difficult to Review

#99 task/87-swim-lines-screen
  build.gradle.kts
  src/main/kotlin/data/dataSource/taskState/TaskStateCSVDataSource.kt
  src/main/kotlin/data/repositories/mappers/TaskMapper.kt
  src/main/kotlin/data/repositories/mappers/TaskStateMapper.kt
  src/main/kotlin/data/resource/audit.csv
  src/main/kotlin/data/resource/tasks_file.csv
  src/main/kotlin/data/resource/users_file.csv
  src/main/kotlin/di/presentationModule.kt
  src/main/kotlin/domain/Validator/TaskStateInputValidator.kt
  src/main/kotlin/domain/usecases/taskState/ExistsTaskStateUseCase.kt
  src/main/kotlin/domain/usecases/taskState/GetAllTaskStatesUseCase.kt
  src/main/kotlin/presentation/cli/TaskState/CreateTaskStateCli.kt
  src/main/kotlin/presentation/cli/TaskState/EditTaskStateCli.kt
  src/main/kotlin/presentation/cli/TaskState/TaskStateInputHandler.kt
  src/main/kotlin/presentation/cli/TaskState/TaskStateShowMenu.kt
  src/main/kotlin/presentation/cli/auth/LoginCli.kt
  src/main/kotlin/presentation/cli/dashBoard/AdminDashBoardCli.kt
  src/main/kotlin/presentation/cli/helper/ProjectCliHelper.kt
  src/test/kotlin/domain/usecases/GetTasksUseCaseTest.kt
  src/test/kotlin/domain/usecases/project/GetAllProjectsUseCaseTest.kt
  src/test/kotlin/domain/usecases/taskState/ExistsTaskStateUseCaseTest.kt
  src/test/kotlin/dummyData/dummyTask.kt
  src/test/kotlin/presentation/cli/TaskState/DeleteTaskStateCliTest.kt
  src/test/kotlin/presentation/cli/TaskState/TaskStateCliControllerTest.kt
  src/test/kotlin/presentation/cli/helper/ProjectCliHelperTest.kt
  src/test/kotlin/presentation/cli/task/CreateTaskCliTest.kt
Labels: Difficult to Review

#93 setup mongodb and coroutine dependencies and connect with mongon database
  build.gradle.kts
  src/main/kotlin/di/mongoModule.kt
  src/main/kotlin/presentation/Main.kt
Labels: Easy to Review

#102 connecting task cli screens
  src/main/kotlin/di/presentationModule.kt
  src/main/kotlin/di/useCaseModule.kt
  src/main/kotlin/presentation/cli/task/ViewSwimlanesCLI.kt
  src/test/kotlin/presentation/cli/task/ViewSwimlanesCLITest.kt
Labels: Easy to Review

#119 refacttoring
  src/main/kotlin/data/dataSource/audit/CsvAuditDataSource.kt
  src/main/kotlin/data/dataSource/project/CsvProjectDataSource.kt
  src/main/kotlin/data/dataSource/task/CsvTaskDataSource.kt
  src/main/kotlin/data/dataSource/taskState/TaskStateCSVDataSource.kt
  src/main/kotlin/data/dataSource/user/CsvUserDataSource.kt
  src/main/kotlin/data/repositories/AuditRepositoryImpl.kt
  src/main/kotlin/data/repositories/ProjectRepositoryImpl.kt
  src/main/kotlin/data/repositories/TaskRepositoryImpl.kt
  src/main/kotlin/data/repositories/TaskStateRepositoryImpl.kt
  src/main/kotlin/data/repositories/UserRepositoryImpl.kt
  src/main/kotlin/data/repositories/dataSource/AuditDataSource.kt
  src/main/kotlin/data/repositories/dataSource/ProjectDataSource.kt
  src/main/kotlin/data/repositories/dataSource/TaskDataSource.kt
  src/main/kotlin/data/repositories/dataSource/TaskStateDataSource.kt
  src/main/kotlin/data/repositories/dataSource/UserDataSource.kt
  src/main/kotlin/di/dataSourceModule.kt
  src/main/kotlin/domain/customeExceptions/AuthenticationExceptions.kt
  src/test/kotlin/data/repositories/ProjectRepositoryImplTest.kt
  src/test/kotlin/data/repositories/TaskRepositoryImplTest.kt
Labels: Moderate Review Effort

#112 migrate the project to mongo
  src/main/kotlin/data/dataSource/project/CsvProjectDataSource.kt
  src/main/kotlin/data/dataSource/project/MongoProjectDataSource.kt
  src/main/kotlin/data/dataSource/project/ProjectDataSource.kt
  src/main/kotlin/data/dataSource/project/ProjectDtoParser.kt
  src/main/kotlin/data/dto/ProjectDto.kt
  src/main/kotlin/data/repositories/ProjectRepositoryImpl.kt
  src/main/kotlin/data/repositories/mappers/Mapper.kt
  src/main/kotlin/data/repositories/mappers/ProjectDtoMapper.kt
  src/main/kotlin/data/repositories/mappers/ProjectMapper.kt
  src/main/kotlin/di/dataSourceModule.kt
  src/main/kotlin/di/mapperModule.kt
  src/main/kotlin/di/mongoModule.kt
  src/main/kotlin/domain/repositories/ProjectRepository.kt
  src/main/kotlin/domain/usecases/project/CreateProjectUseCase.kt
  src/main/kotlin/domain/usecases/project/DeleteProjectUseCase.kt
  src/main/kotlin/domain/usecases/project/GetAllProjectsUseCase.kt
  src/main/kotlin/domain/usecases/project/UpdateProjectUseCase.kt
  src/main/kotlin/presentation/Main.kt
  src/main/kotlin/presentation/cli/helper/ProjectCliHelper.kt
  src/main/kotlin/presentation/cli/project/CreateProjectCli.kt
  src/main/kotlin/presentation/cli/project/DeleteProjectCli.kt
  src/main/kotlin/presentation/cli/project/GetAllProjectsCli.kt
  src/main/kotlin/presentation/cli/project/ProjectScreenController.kt
  src/main/kotlin/presentation/cli/project/UpdateProjectCli.kt
  src/main/kotlin/presentation/cli/taskState/TaskStateCliController.kt
  src/test/kotlin/data/dataSource/project/CsvProjectDataSourceTest.kt
  src/test/kotlin/data/dataSource/project/MongoProjectDataSourceIntegrationTest.kt
  src/test/kotlin/data/dataSource/project/ProjectDtoParserTest.kt
  src/test/kotlin/data/dataSource/user/MongoUserDataSourceTest.kt
  src/test/kotlin/data/repositories/ProjectRepositoryImplTest.kt
  src/test/kotlin/data/repositories/mappers/ProjectDtoMapperTest.kt
  src/test/kotlin/domain/usecases/project/CreateProjectUseCaseTest.kt
  src/test/kotlin/domain/usecases/project/DeleteProjectUseCaseTest.kt
  src/test/kotlin/domain/usecases/project/GetAllProjectsUseCaseTest.kt
  src/test/kotlin/domain/usecases/project/UpdateProjectUseCaseTest.kt
  src/test/kotlin/dummyData/createDummyProjects.kt
  src/test/kotlin/presentation/cli/helper/ProjectCliHelperTest.kt
  src/test/kotlin/presentation/cli/project/CreateProjectCliTest.kt
  src/test/kotlin/presentation/cli/project/DeleteProjectCliTest.kt
  src/test/kotlin/presentation/cli/project/GetAllProjectsCliTest.kt
  src/test/kotlin/presentation/cli/project/ProjectScreenControllerTest.kt
  src/test/kotlin/presentation/cli/project/UpdateProjectCliTest.kt
  src/test/kotlin/presentation/cli/taskState/TaskStateCliControllerTest.kt
Labels: Difficult to Review

#130 change validator class to mockk in test other classes and create vali…
  src/main/kotlin/di/domainUtilModule.kt
  src/main/kotlin/domain/entities/TaskStateWithTasks.kt
  src/main/kotlin/domain/usecases/AuthenticationUseCase.kt
  src/main/kotlin/domain/usecases/CreateUserUseCase.kt
  src/main/kotlin/domain/usecases/GetTasksGroupedByStateUseCase.kt
  src/main/kotlin/domain/validation/UserValidator.kt
  src/main/kotlin/presentation/cli/task/ViewSwimlanesCLI.kt
  src/test/kotlin/domain/usecases/AuthenticationUseCaseTest.kt
  src/test/kotlin/domain/usecases/CreateUserUseCaseTest.kt
  src/test/kotlin/domain/validation/UserValidatorTest.kt
  src/test/kotlin/presentation/cli/task/ViewSwimlanesCLITest.kt
Labels: Moderate Review Effort

#133 task/125-throw-exception-from-the-repository-and-dont-return-null
  src/main/kotlin/data/dataSource/audit/CsvAuditDataSource.kt
  src/main/kotlin/data/dataSource/project/CsvProjectDataSource.kt
  src/main/kotlin/data/dataSource/project/MongoProjectDataSource.kt
  src/main/kotlin/data/dataSource/task/CsvTaskDataSource.kt
  src/main/kotlin/data/dataSource/task/MongoTaskDataSource.kt
  src/main/kotlin/data/repositories/ProjectRepositoryImpl.kt
  src/main/kotlin/data/repositories/dataSource/ProjectDataSource.kt
  src/main/kotlin/data/repositories/dataSource/TaskDataSource.kt
  src/main/kotlin/di/presentationModule.kt
  src/main/kotlin/domain/customeExceptions/UserEnterInvalidValueException.kt
  src/main/kotlin/domain/repositories/ProjectRepository.kt
  src/main/kotlin/domain/usecases/AddAuditUseCase.kt
  src/main/kotlin/domain/usecases/GetTasksGroupedByStateUseCase.kt
  src/main/kotlin/domain/usecases/project/GetAllProjectsUseCase.kt
  src/main/kotlin/presentation/cli/GetAllAuditsCli.kt
  src/main/kotlin/presentation/cli/helper/ProjectCliHelper.kt
  src/main/kotlin/presentation/cli/project/CreateProjectCli.kt
  src/main/kotlin/presentation/cli/project/DeleteProjectCli.kt
  src/main/kotlin/presentation/cli/project/GetAllProjectsCli.kt
  src/main/kotlin/presentation/cli/project/ProjectScreenController.kt
  src/main/kotlin/presentation/cli/project/UpdateProjectCli.kt
  src/main/kotlin/presentation/cli/task/ViewSwimlanesCLI.kt
  src/main/kotlin/presentation/cli/taskState/TaskStateCliController.kt
  src/test/kotlin/data/dataSource/audit/CsvAuditDataSourceTest.kt
  src/test/kotlin/data/dataSource/project/CsvProjectDataSourceTest.kt
  src/test/kotlin/data/dataSource/project/MongoProjectDataSourceIntegrationTest.kt
  src/test/kotlin/data/dataSource/task/CsvTaskDataSourceTest.kt
  src/test/kotlin/data/dataSource/task/MongoTaskDataSourceTest.kt
  src/test/kotlin/data/repositories/ProjectRepositoryImplTest.kt
  src/test/kotlin/domain/customeExceptions/NoProjectsFoundExceptionTest.kt
  src/test/kotlin/domain/customeExceptions/UserEnterInvalidValueExceptionTest.kt
  src/test/kotlin/domain/usecases/AddAuditUseCaseTest.kt
  src/test/kotlin/domain/usecases/AuthenticationUseCaseTest.kt
  src/test/kotlin/domain/usecases/project/GetAllProjectsUseCaseTest.kt
  src/test/kotlin/domain/validation/UserValidatorTest.kt
  src/test/kotlin/presentation/cli/GetAllAuditsCliTest.kt
  src/test/kotlin/presentation/cli/helper/ProjectCliHelperTest.kt
  src/test/kotlin/presentation/cli/project/CreateProjectCliTest.kt
  src/test/kotlin/presentation/cli/project/DeleteProjectCliTest.kt
  src/test/kotlin/presentation/cli/project/GetAllProjectsCliTest.kt
  src/test/kotlin/presentation/cli/project/ProjectScreenControllerTest.kt
  src/test/kotlin/presentation/cli/project/UpdateProjectCliTest.kt
Labels: Difficult to Review

#134 injecting refactor
  src/main/kotlin/di/dataSourceModule.kt
  src/main/kotlin/di/dataUtilModule.kt
  src/main/kotlin/di/domainUtilModule.kt
  src/main/kotlin/di/mapperModule.kt
  src/main/kotlin/di/presentationModule.kt
  src/main/kotlin/di/useCaseModule.kt
Labels: Difficult to Review

#140 Task/124 remove password from entity and handle when user is null
  src/main/kotlin/data/dto/UserDto.kt
  src/main/kotlin/data/exceptions/Exception.kt
  src/main/kotlin/data/exceptions/TaskStateNameException.kt
  src/main/kotlin/data/repositories/AuthRepositoryImpl.kt
  src/main/kotlin/data/repositories/UserRepositoryImpl.kt
  src/main/kotlin/data/repositories/mappers/UserDtoMapper.kt
  src/main/kotlin/di/repositoryModule.kt
  src/main/kotlin/domain/customeExceptions/AuthenticationExceptions.kt
  src/main/kotlin/domain/entities/User.kt
  src/main/kotlin/domain/repositories/AuthRepository.kt
  src/main/kotlin/domain/repositories/UserRepository.kt
  src/main/kotlin/domain/usecases/AuthenticationUseCase.kt
  src/main/kotlin/domain/usecases/CreateUserUseCase.kt
  src/main/kotlin/domain/usecases/task/CreateTaskUseCase.kt
  src/main/kotlin/domain/usecases/task/DeleteTaskUseCase.kt
  src/main/kotlin/domain/usecases/task/UpdateTaskUseCase.kt
  src/main/kotlin/domain/validation/UserValidator.kt
  src/main/kotlin/presentation/cli/auth/CreateUserCli.kt
  src/main/kotlin/presentation/cli/auth/LoginCli.kt
  src/main/kotlin/presentation/cli/task/CreateTaskCli.kt
  src/main/kotlin/presentation/cli/task/DeleteTaskCli.kt
  src/main/kotlin/presentation/cli/task/UpdateTaskCli.kt
  src/main/kotlin/presentation/exceptions/AuthenticationExceptions.kt
  src/main/kotlin/presentation/exceptions/Exception.kt
  src/test/kotlin/data/dataSource/user/UserDtoParserTest.kt
  src/test/kotlin/data/repositories/AuthRepositoryImplTest.kt
  src/test/kotlin/data/repositories/UserRepositoryImplTest.kt
  src/test/kotlin/data/repositories/mappers/TaskDtoMapperTest.kt
  src/test/kotlin/domain/usecases/AuthenticationUseCaseTest.kt
  src/test/kotlin/domain/usecases/CreateUserUseCaseTest.kt
  src/test/kotlin/domain/usecases/task/CreateTaskUseCaseTest.kt
  src/test/kotlin/domain/usecases/task/DeleteTaskUseCaseTest.kt
  src/test/kotlin/domain/usecases/task/GetAllTasksUseCaseTest.kt
  src/test/kotlin/domain/usecases/task/UpdateTaskUseCaseTest.kt
  src/test/kotlin/domain/validation/UserValidatorTest.kt
  src/test/kotlin/dummyData/CreateDummyUser.kt
  src/test/kotlin/dummyData/DummyTaskData.kt
  src/test/kotlin/dummyData/DummyUser.kt
  src/test/kotlin/presentation/cli/auth/CreateUserCliTest.kt
  src/test/kotlin/presentation/cli/auth/LoginCliTest.kt
  src/test/kotlin/presentation/cli/task/CreateTaskCliTest.kt
  src/test/kotlin/presentation/cli/task/DeleteTaskCliTest.kt
  src/test/kotlin/presentation/cli/task/UpdateTaskCliTest.kt
Labels: Difficult to Review

#132 hidde mongo connection string
  .gitignore
  build.gradle.kts
  src/main/kotlin/config/AppConfig.kt
  src/main/kotlin/di/mongoModule.kt
Labels: Easy to Review

#152 change test classes that was injected to be mockked
  src/test/kotlin/data/dataSource/audit/CsvAuditDataSourceTest.kt
  src/test/kotlin/data/dataSource/task/CsvTaskDataSourceTest.kt
  src/test/kotlin/data/dataSource/taskState/TaskStateCSVDataSourceTest.kt
  src/test/kotlin/data/dataSource/user/CsvUserDataSourceTest.kt
  src/test/kotlin/data/dataSource/util/CsvHandlerTest.kt
  src/test/kotlin/data/repositories/AuditRepositoryImplTest.kt
  src/test/kotlin/data/repositories/TaskStateRepositoryImplTest.kt
Labels: Difficult to Review

#150 add abstraction for password hashing and update tests
  src/main/kotlin/data/dataSource/util/PasswordHash.kt
  src/main/kotlin/data/dataSource/util/hash/MD5PasswordHash.kt
  src/main/kotlin/data/dataSource/util/hash/PasswordHash.kt
  src/main/kotlin/data/repositories/UserRepositoryImpl.kt
  src/main/kotlin/di/dataUtilModule.kt
  src/test/kotlin/data/dataSource/util/hash/MD5PasswordHashTest.kt
  src/test/kotlin/data/repositories/AuthRepositoryImplTest.kt
  src/test/kotlin/data/repositories/UserRepositoryImplTest.kt
Labels: Moderate Review Effort

#151 145-refactor-dto-classes
  src/main/kotlin/data/dataSource/audit/AuditDtoParser.kt
  src/main/kotlin/data/dto/AuditDto.kt
  src/main/kotlin/data/repositories/mappers/AuditDtoMapper.kt
  src/test/kotlin/data/dataSource/audit/AuditDtoParserTest.kt
  src/test/kotlin/data/dataSource/audit/MongoAuditDataSourceTest.kt
  src/test/kotlin/data/dummyData/DummyAudits.kt
  src/test/kotlin/domain/usecases/AddAuditUseCaseTest.kt
Labels: Easy to Review

#154 refactor property names
  src/main/kotlin/data/repositories/ProjectRepositoryImpl.kt
  src/main/kotlin/data/repositories/TaskStateRepositoryImpl.kt
  src/main/kotlin/data/repositories/mappers/AuditDtoMapper.kt
  src/main/kotlin/data/repositories/mappers/ProjectDtoMapper.kt
  src/main/kotlin/data/repositories/mappers/TaskStateDtoMapper.kt
  src/main/kotlin/domain/entities/Audit.kt
  src/main/kotlin/domain/entities/Project.kt
  src/main/kotlin/domain/entities/TaskState.kt
  src/main/kotlin/domain/usecases/AddAuditUseCase.kt
  src/main/kotlin/presentation/cli/GetAllAuditsCli.kt
  src/main/kotlin/presentation/cli/helper/ProjectCliHelper.kt
  src/main/kotlin/presentation/cli/project/CreateProjectCli.kt
  src/main/kotlin/presentation/cli/project/GetAllProjectsCli.kt
  src/main/kotlin/presentation/cli/project/UpdateProjectCli.kt
  src/main/kotlin/presentation/cli/task/CreateTaskCli.kt
  src/main/kotlin/presentation/cli/task/TaskCliUtils.kt
  src/main/kotlin/presentation/cli/task/ViewSwimlanesCLI.kt
  src/main/kotlin/presentation/cli/taskState/CreateTaskStateCli.kt
  src/main/kotlin/presentation/cli/taskState/EditTaskStateCli.kt
  src/main/kotlin/presentation/cli/taskState/TaskStateInputHandler.kt
  src/main/kotlin/presentation/cli/taskState/TaskStatePrinter.kt
  src/test/kotlin/data/dataSource/dummyData/createDummyAudits.kt
  src/test/kotlin/data/dummyData/DummyAudits.kt
  src/test/kotlin/data/repositories/TaskStateRepositoryImplTest.kt
  src/test/kotlin/data/repositories/mappers/ProjectDtoMapperTest.kt
  src/test/kotlin/domain/usecases/AddAuditUseCaseTest.kt
  src/test/kotlin/dummyData/DummyTaskData.kt
  src/test/kotlin/dummyData/createDummyProjects.kt
  src/test/kotlin/dummyData/dummyStateData/DummyTaskState.kt
  src/test/kotlin/dummyData/dummyStateData/createDummyTaskState.kt
  src/test/kotlin/presentation/cli/project/UpdateProjectCliTest.kt
  src/test/kotlin/presentation/cli/task/CreateTaskCliTest.kt
  src/test/kotlin/presentation/cli/taskState/CreateTaskStateCliTest.kt
  src/test/kotlin/presentation/cli/taskState/EditTaskStateCliTest.kt
Labels: Moderate Review Effort

#153 refactor packages and use cases names
  src/main/kotlin/data/dataSource/audit/AuditDtoParser.kt
  src/main/kotlin/data/dataSource/project/ProjectDtoParser.kt
  src/main/kotlin/data/dataSource/resource/audit.csv
  src/main/kotlin/data/dataSource/resource/projects.csv
  src/main/kotlin/data/dataSource/resource/task_state.csv
  src/main/kotlin/data/dataSource/resource/tasks_file.csv
  src/main/kotlin/data/dataSource/resource/users_file.csv
  src/main/kotlin/data/dataSource/task/TaskDtoParser.kt
  src/main/kotlin/data/dataSource/taskState/TaskStateDtoParser.kt
  src/main/kotlin/data/dataSource/user/UserDtoParser.kt
  src/main/kotlin/data/dto/DtoParser.kt
  src/main/kotlin/di/presentationModule.kt
  src/main/kotlin/di/useCaseModule.kt
  src/main/kotlin/domain/usecases/audit/AddAuditUseCase.kt
  src/main/kotlin/domain/usecases/audit/GetAllAuditUseCase.kt
  src/main/kotlin/domain/usecases/auth/LoginUseCase.kt
  src/main/kotlin/domain/usecases/groupingByState/GetTasksGroupedByStateUseCase.kt
  src/main/kotlin/domain/usecases/task/CreateTaskUseCase.kt
  src/main/kotlin/domain/usecases/task/DeleteTaskUseCase.kt
  src/main/kotlin/domain/usecases/task/GetTasksUseCase.kt
  src/main/kotlin/domain/usecases/task/UpdateTaskUseCase.kt
  src/main/kotlin/domain/usecases/taskState/CreateTaskStateUseCase.kt
  src/main/kotlin/domain/usecases/user/CreateUserUseCase.kt
  src/main/kotlin/presentation/cli/MainCli.kt
  src/main/kotlin/presentation/cli/audit/GetAllAuditsCli.kt
  src/main/kotlin/presentation/cli/auth/CreateUserCli.kt
  src/main/kotlin/presentation/cli/auth/LoginCli.kt
  src/main/kotlin/presentation/cli/dashBoard/AdminDashBoardCli.kt
  src/main/kotlin/presentation/cli/task/CreateTaskCli.kt
  src/main/kotlin/presentation/cli/task/DeleteTaskCli.kt
  src/main/kotlin/presentation/cli/task/UpdateTaskCli.kt
  src/main/kotlin/presentation/cli/task/ViewSwimlanesCLI.kt
  src/main/kotlin/presentation/cli/taskState/CreateTaskStateCli.kt
  src/test/kotlin/domain/usecases/audit/AddAuditUseCaseTest.kt
  src/test/kotlin/domain/usecases/audit/GetAllAuditUseCaseTest.kt
  src/test/kotlin/domain/usecases/auth/LoginUseCaseTest.kt
  src/test/kotlin/domain/usecases/groupingByState/GetTasksGroupedByStateUseCaseTest.kt
  src/test/kotlin/domain/usecases/task/CreateTaskUseCaseTest.kt
  src/test/kotlin/domain/usecases/task/DeleteTaskUseCaseTest.kt
  src/test/kotlin/domain/usecases/task/GetTasksUseCaseTest.kt
  src/test/kotlin/domain/usecases/task/UpdateTaskUseCaseTest.kt
  src/test/kotlin/domain/usecases/taskState/CreateTaskStateUseCaseTest.kt
  src/test/kotlin/domain/usecases/user/CreateUserUseCaseTest.kt
  src/test/kotlin/presentation/cli/MainCliTest.kt
  src/test/kotlin/presentation/cli/audit/GetAllAuditsCliTest.kt
  src/test/kotlin/presentation/cli/auth/CreateUserCliTest.kt
  src/test/kotlin/presentation/cli/auth/LoginCliTest.kt
  src/test/kotlin/presentation/cli/dashBoard/AdminDashBoardCliTest.kt
  src/test/kotlin/presentation/cli/task/CreateTaskCliTest.kt
  src/test/kotlin/presentation/cli/task/DeleteTaskCliTest.kt
  src/test/kotlin/presentation/cli/task/UpdateTaskCliTest.kt
  src/test/kotlin/presentation/cli/task/ViewSwimlanesCLITest.kt
  src/test/kotlin/presentation/cli/taskState/CreateTaskStateCliTest.kt
Labels: Difficult to Review

#156 change hard coded strings to be constant
  src/main/kotlin/data/dataSource/project/ProjectDtoParser.kt
  src/main/kotlin/data/repositories/mappers/CsvTaskMapper.kt
  src/main/kotlin/presentation/cli/audit/GetAllAuditsCli.kt
  src/main/kotlin/presentation/cli/auth/LoginCli.kt
  src/main/kotlin/presentation/cli/dashBoard/MateDashBoardCli.kt
  src/main/kotlin/presentation/cli/helper/ProjectCliHelper.kt
  src/main/kotlin/presentation/cli/project/CreateProjectCli.kt
  src/main/kotlin/presentation/cli/project/DeleteProjectCli.kt
  src/main/kotlin/presentation/cli/project/GetAllProjectsCli.kt
  src/main/kotlin/presentation/cli/project/ProjectScreenController.kt
  src/main/kotlin/presentation/cli/project/ProjectShowMenu.kt
  src/main/kotlin/presentation/cli/project/UpdateProjectCli.kt
  src/main/kotlin/presentation/cli/task/CreateTaskCli.kt
  src/main/kotlin/presentation/cli/task/DeleteTaskCli.kt
  src/main/kotlin/presentation/cli/task/TaskCliUtils.kt
  src/main/kotlin/presentation/cli/task/UpdateTaskCli.kt
  src/main/kotlin/presentation/cli/task/ViewSwimlanesCLI.kt
  src/main/kotlin/presentation/cli/taskState/CreateTaskStateCli.kt
  src/main/kotlin/presentation/cli/taskState/DeleteTaskStateCli.kt
  src/main/kotlin/presentation/cli/taskState/EditTaskStateCli.kt
  src/main/kotlin/presentation/cli/taskState/GetAllTaskStatesCli.kt
  src/main/kotlin/presentation/cli/taskState/TaskStateCliController.kt
  src/main/kotlin/presentation/cli/taskState/TaskStateInputHandler.kt
  src/main/kotlin/presentation/cli/taskState/TaskStatePrinter.kt
  src/test/kotlin/data/repositories/mappers/csvTaskMapperTest.kt
  src/test/kotlin/presentation/cli/helper/ProjectCliHelperTest.kt
  src/test/kotlin/presentation/cli/project/CreateProjectCliTest.kt
  src/test/kotlin/presentation/cli/project/DeleteProjectCliTest.kt
  src/test/kotlin/presentation/cli/project/UpdateProjectCliTest.kt
  src/test/kotlin/presentation/cli/task/CreateTaskCliTest.kt
  src/test/kotlin/presentation/cli/task/ViewSwimlanesCLITest.kt
  src/test/kotlin/presentation/cli/taskState/CreateTaskStateCliTest.kt
  src/test/kotlin/presentation/cli/taskState/TaskStateCliControllerTest.kt
Labels: Difficult to Review

#159 delete parser interface and depend on mapper
  src/main/kotlin/data/dataSource/audit/AuditDtoParser.kt
  src/main/kotlin/data/dataSource/audit/CsvAuditDataSource.kt
  src/main/kotlin/data/dataSource/project/CsvProjectDataSource.kt
  src/main/kotlin/data/dataSource/project/ProjectDtoParser.kt
  src/main/kotlin/data/dataSource/task/CsvTaskDataSource.kt
  src/main/kotlin/data/dataSource/task/TaskDtoParser.kt
  src/main/kotlin/data/dataSource/taskState/CsvTaskStateDataSource.kt
  src/main/kotlin/data/dataSource/taskState/TaskStateDtoParser.kt
  src/main/kotlin/data/dataSource/user/CsvUserDataSource.kt
  src/main/kotlin/data/dataSource/user/UserDtoParser.kt
  src/main/kotlin/data/dto/DtoParser.kt
  src/main/kotlin/data/repositories/AuditRepositoryImpl.kt
  src/main/kotlin/data/repositories/ProjectRepositoryImpl.kt
  src/main/kotlin/data/repositories/TaskRepositoryImpl.kt
  src/main/kotlin/data/repositories/TaskStateRepositoryImpl.kt
  src/main/kotlin/data/repositories/UserRepositoryImpl.kt
  src/main/kotlin/data/repositories/mappers/AuditDtoMapper.kt
  src/main/kotlin/data/repositories/mappers/Mapper.kt
  src/main/kotlin/data/repositories/mappers/ProjectDtoMapper.kt
  src/main/kotlin/data/repositories/mappers/TaskDtoMapper.kt
  src/main/kotlin/data/repositories/mappers/TaskStateDtoMapper.kt
  src/main/kotlin/data/repositories/mappers/UserDtoMapper.kt
  src/test/kotlin/data/dataSource/audit/AuditDtoParserTest.kt
  src/test/kotlin/data/dataSource/audit/CsvAuditDataSourceTest.kt
  src/test/kotlin/data/dataSource/dummyData/createDummyAudits.kt
  src/test/kotlin/data/dataSource/project/CsvProjectDataSourceTest.kt
  src/test/kotlin/data/dataSource/project/ProjectDtoParserTest.kt
  src/test/kotlin/data/dataSource/task/CsvTaskDataSourceTest.kt
  src/test/kotlin/data/dataSource/taskState/CsvTaskStateDataSourceTest.kt
  src/test/kotlin/data/dataSource/user/CsvUserDataSourceTest.kt
  src/test/kotlin/data/dataSource/user/UserDtoParserTest.kt
  src/test/kotlin/data/repositories/AuditRepositoryImplTest.kt
  src/test/kotlin/data/repositories/ProjectRepositoryImplTest.kt
  src/test/kotlin/data/repositories/TaskRepositoryImplTest.kt
  src/test/kotlin/data/repositories/TaskStateRepositoryImplTest.kt
  src/test/kotlin/data/repositories/UserRepositoryImplTest.kt
  src/test/kotlin/data/repositories/mappers/AuditDtoMapperTest.kt
  src/test/kotlin/data/repositories/mappers/ProjectDtoMapperTest.kt
  src/test/kotlin/data/repositories/mappers/TaskDtoMapperTest.kt
  src/test/kotlin/data/repositories/mappers/TaskStateMapperTest.kt
  src/test/kotlin/data/repositories/mappers/UserDtoMapperTest.kt
  src/test/kotlin/domain/usecases/audit/AddAuditUseCaseTest.kt
Labels: Difficult to Review

#155 task/148-create-wrapper-function-to-be-applied-in-all-repositories-actions
  src/main/kotlin/auth/UserSession.kt
  src/main/kotlin/auth/UserSessionImpl.kt
  src/main/kotlin/data/dto/TaskDto.kt
  src/main/kotlin/data/exceptions/Exception.kt
  src/main/kotlin/data/repositories/AuditRepositoryImpl.kt
  src/main/kotlin/data/repositories/AuthRepositoryImpl.kt
  src/main/kotlin/data/repositories/ProjectRepositoryImpl.kt
  src/main/kotlin/data/repositories/TaskRepositoryImpl.kt
  src/main/kotlin/data/repositories/TaskStateRepositoryImpl.kt
  src/main/kotlin/data/repositories/UserRepositoryImpl.kt
  src/main/kotlin/data/repositories/mappers/TaskDtoMapper.kt
  src/main/kotlin/di/dataUtilModule.kt
  src/main/kotlin/di/presentationModule.kt
  src/main/kotlin/di/repositoryModule.kt
  src/main/kotlin/di/useCaseModule.kt
  src/main/kotlin/domain/entities/Task.kt
  src/main/kotlin/domain/repositories/AuthRepository.kt
  src/main/kotlin/domain/repositories/TaskRepository.kt
  src/main/kotlin/domain/repositories/UserRepository.kt
  src/main/kotlin/domain/usecases/audit/AddAuditUseCase.kt
  src/main/kotlin/domain/usecases/auth/LoginUseCase.kt
  src/main/kotlin/domain/usecases/task/AddTaskUseCase.kt
  src/main/kotlin/domain/usecases/task/CreateTaskUseCase.kt
  src/main/kotlin/domain/usecases/task/DeleteTaskUseCase.kt
  src/main/kotlin/domain/usecases/task/UpdateTaskUseCase.kt
  src/main/kotlin/domain/usecases/user/CreateUserUseCase.kt
  src/main/kotlin/presentation/cli/helper/TaskStateCliHelper.kt
  src/main/kotlin/presentation/cli/project/CreateProjectCli.kt
  src/main/kotlin/presentation/cli/project/GetAllProjectsCli.kt
  src/main/kotlin/presentation/cli/task/CreateTaskCli.kt
  src/main/kotlin/presentation/cli/task/TaskCliUtils.kt
  src/main/kotlin/presentation/cli/task/UpdateTaskCli.kt
  src/main/kotlin/presentation/cli/task/ViewSwimlanesCLI.kt
  src/test/kotlin/auth/FakeUserSession.kt
  src/test/kotlin/auth/UserSessionImplTest.kt
  src/test/kotlin/data/dataSource/dummyData/DummyTasks.kt
  src/test/kotlin/data/repositories/AuthRepositoryImplTest.kt
  src/test/kotlin/data/repositories/ProjectRepositoryImplTest.kt
  src/test/kotlin/data/repositories/TaskRepositoryImplTest.kt
  src/test/kotlin/data/repositories/TaskStateRepositoryImplTest.kt
  src/test/kotlin/data/repositories/UserRepositoryImplTest.kt
  src/test/kotlin/domain/usecases/project/GetAllProjectsUseCaseTest.kt
  src/test/kotlin/domain/usecases/task/CreateTaskUseCaseTest.kt
  src/test/kotlin/domain/usecases/task/DeleteTaskUseCaseTest.kt
  src/test/kotlin/domain/usecases/task/UpdateTaskUseCaseTest.kt
  src/test/kotlin/domain/usecases/user/CreateUserUseCaseTest.kt
  src/test/kotlin/dummyData/DummyTasks.kt
  src/test/kotlin/dummyData/DummyUser.kt
  src/test/kotlin/dummyData/createDummyProjects.kt
  src/test/kotlin/dummyData/createDummyTask.kt
  src/test/kotlin/presentation/cli/project/CreateProjectCliTest.kt
  src/test/kotlin/presentation/cli/project/GetAllProjectsCliTest.kt
  src/test/kotlin/presentation/cli/task/CreateTaskCliTest.kt
  src/test/kotlin/presentation/cli/task/TaskCliUtilsTest.kt
  src/test/kotlin/presentation/cli/task/UpdateTaskCliTest.kt
  src/test/kotlin/presentation/cli/task/ViewSwimlanesCLITest.kt
Labels: Difficult to Review
